### ISSUE TITLE
Adding a zfs backed disk doesn't create the storage

### ISSUE THREAD

**Issue by Cadair** [Telmate/terraform-provider-proxmox#138]
I am trying to add a second disk backed by zfs I have the following in my file:

```
    disk {
        id = 0
        size = 64
        type = "scsi"
        storage = "storage"
        storage_type = "zfspool"
    }

    disk {
        id = 2
        size = 128
        type = "scsi"
        storage = "storage"
        storage_type = "zfspool"
    }
```

The plan executes happily and all seems well, but the second disk is never created. In the proxmox console I see under the "configure" task for the VM:
```
**TASK ERROR: zfs error: cannot open 'storage/vm-114-disk-2': dataset does not exist**
```
It seems it's not creating the underlying storage before it tries to use it? Have I missed a step or something?

The first disk is there as I would expect (but I think it's copied from the template anyway).

**Comment by tisc0** [comment]
Hi,
I just succeeded, inspired of your config to correct my mistake. But...
Your error seems to indicate that your `dataset does not exist`, which I find a bit deceiving since the value for `storage` in my setup IS NOT my actual dataset name, but the storage name I choose to attach to a dataset (name you can get in your proxmox webUI::Datacenter/storage).
I think it's worth checking (and for the dev team, maybe change the error message ?).

Also, are you sure [ you're not | you don't want to ] use 'virtio' ?

My working config:
```
  disk {
    id              = 0
    size            = 20
    type            = "virtio"
    storage         = "local-zfs"
    storage_type    = "zfspool"
    iothread        = true
  }
```
Hope it helps,
Good luck !
