### ISSUE TITLE
Error: Proxmox Provider Error: proxmox API returned new disk parameter 'slot' we cannot process

### ISSUE THREAD

**Issue by jospanier** [Telmate/terraform-provider-proxmox#237]
I always get the following error when applying any state file

`Error: Proxmox Provider Error: proxmox API returned new disk parameter 'slot' we cannot process
`

provider log shows the following API response (relevant snippet, formatted)
```
"disk":{
  "0":{
    "file":"102/vm-102-disk-0.qcow2",
	"size":"10G",
	"slot":0,
	"storage":"<redacted>",
	"type":"scsi",
	"volume":"<redacted>:102/vm-102-disk-0.qcow2"
  }
}
```
terraform version
Terraform v0.13.5
provider registry.terraform.io/telmate/proxmox v2.6.2

pveversion
pve-manager/6.2-15/48bd51b6 (running kernel: 5.4.65-1-pve)

**Comment by kainefoto** [comment]
I had the same error yesterday. In fact I had to revert the upgrade to an older version. In my case:
- Terraform v0.12.29
- pve-manager 6.2-15  (kernel: 5.4.65-1-pve)

**Comment by doransmestad** [comment]
Working on this.  For context:  this error is a safety valve to prevent an accidental disk overwrite when a new (and unknown) value is returned by the API.  Adding this new field to the provider is easy, but unfortunately there is another error underneath this one causing a crash due to what looks like a couple conflicting changes.  I'll post a PR once I sort this out.  Thank you for reporting it!

**Comment by doransmestad** [comment]
Hey @jospanier-  have you had a chance to try the fix?  All set?  Can we close out this ticket?

**Comment by jospanier** [comment]
Ah, sorry. busy, busy
Yes, works like a charm now.
Much appreciated. Many Thanks
