### ISSUE TITLE
Unable to disable disk backup

### ISSUE THREAD

**Issue by Tinyblargon** [Telmate/terraform-provider-proxmox#429]
setting the backup propertie to 0 does not unset the backup check mark in the proxmox gui.

```
  disk {
    type = "scsi"
    storage = "local-lvm"
    size = "2G"
    backup = "0"
  }
```

When unchecking the backup checkbox inside the proxmox gui the disk configuration is as followed:
`local-lvm:vm-9001-disk-0,backup=0,size=2G`

When setting `backup = "0"` in terraform it results in:
`local-lvm:vm-9001-disk-0,size=2G`
By default backup is turned on in proxmox and only shows in the disk configuration when it is disabled.
The checkbox in the gui is also still checked.
This leeds me to believe that setting `backup = "0"` in terraform did not turn the backup off.

Terraform Provider version = 2.9.0
Proxmox version = 7.0-13

**Comment by n8rade** [comment]
Running into this same issue with the following versions:

PVE 7.2-7
Terraform 1.2.6
Telmate/terraform-provider-proxmox 2.9.10

There's a lot that's interesting about this.
1. The documentation states that the default value is 0 here. https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#disk-block
Despite this being the default (and me missing that the default was to exclude backing up any disks), any new VM I create with this default value is included in any backups I perform.

2. All of the machines that I've imported into my terraform state all have "backup=0" under the disks section, despite all of them being included in backups before I started using Terraform. In other words, Proxmox sees the disks as being available to be backed up. None of them have a "backup=" value defined on the disk, but the box is check marked if I open up the disk to view in the UI.

3. Here are the strange behaviors I see when testing this:

### Test 1:
**State of Disk:** "backup=0" set manually on the disk
**Resource Expects:** "backup=0"
**Terraform Plan:** No changes expected

### Test 2:
**State of Disk:** "backup=0" set manually on the disk
**Resource Expects:** "backup=1"
**Terraform Plan:** Wants to change
**Terraform Apply:** Sets "backup=1" and also checks the "Backup" box in the Proxmox UI

### Configure seen in Proxmox UI from terraform for **Test 2**:
~~~
update VM 125: -agent 1 -bios seabios -boot order=scsi0;ide2;net0 -cores 2 -cpu host -delete balloon, vcpus, vga -hotplug network,disk,usb -ipconfig0 ip=XXX.XXX.XXX/24,gw=XXX.XXX.XXX -kvm 1 -memory 2048 -name hostname -net0 e1000=F6:27:42:5A:8F:E7,bridge=vmbr0,firewall=1 -numa 1 -onboot 1 -scsi0 local:125/vm-125-disk-0.qcow2,size=50G,ssd=1,format=qcow2,backup=1 -scsihw virtio-scsi-pci -sockets 1 -tablet 1
~~~

### Test 3:
**State of Disk:** "backup=1" set from previous apply
**Resource Expects:** "backup=0"
**Terraform Plan:** Wants to change
**Terraform Apply:** States it's changed, but the disk does NOT show "backup=0" and instead has the "Backup" box checked for backup in the Proxomx UI.

### Configure seen in Proxmox UI from terraform for **Test 3**: (It appears to not include "backup=0" here, when I would expect it to)
~~~
update VM 125: -agent 1 -bios seabios -boot order=scsi0;ide2;net0 -cores 2 -cpu host -delete balloon, vcpus, vga -hotplug network,disk,usb -ipconfig0 ip=XXX.XXX.XXX/24,gw=XXX.XXX.XXX -kvm 1 -memory 2048 -name hostname -net0 e1000=F6:27:42:5A:8F:E7,bridge=vmbr0,firewall=1 -numa 1 -onboot 1 -scsi0 local:125/vm-125-disk-0.qcow2,size=50G,ssd=1,format=qcow2 -scsihw virtio-scsi-pci -sockets 1 -tablet 1
~~~

Here's the terraform apply output for Test 3 as seen above:
~~~
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.full-work-creation.module.vm-work-creation["hostname"].proxmox_vm_qemu.vm-work-creation will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm-work-creation" {
        id                        = "proxmox/qemu/125"
        name                      = "hostname"
        # (36 unchanged attributes hidden)

      ~ disk {
          ~ backup       = 1 -> 0
            # (17 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.full-work-creation.module.vm-work-creation["hostname"].proxmox_vm_qemu.vm-work-creation: Modifying... [id=proxmox/qemu/125]
module.full-work-creation.module.vm-work-creation["hostname"].proxmox_vm_qemu.vm-work-creation: Still modifying... [id=proxmox/qemu/125, 10s elapsed]
module.full-work-creation.module.vm-work-creation["hostname"].proxmox_vm_qemu.vm-work-creation: Still modifying... [id=proxmox/qemu/125, 20s elapsed]
module.full-work-creation.module.vm-work-creation["hostname"].proxmox_vm_qemu.vm-work-creation: Still modifying... [id=proxmox/qemu/125, 30s elapsed]
module.full-work-creation.module.vm-work-creation["hostname"].proxmox_vm_qemu.vm-work-creation: Still modifying... [id=proxmox/qemu/125, 40s elapsed]
module.full-work-creation.module.vm-work-creation["hostname"].proxmox_vm_qemu.vm-work-creation: Modifications complete after 48s [id=proxmox/qemu/125]
~~~

I was hoping as a workaround I'd be able to set backup=1 on the template with packer, but with the behavior seen in my tests above it doesn't even seem like that would allow me to set backup=0 when deploying a new terraform VM from the template.

It seems like there's a disconnect between Proxmox and the default value of "backup=0" within the resource/provider. Since Proxmox doesn't seem to define any "backup=1" by default but still checks the "backup" box while not defining anything the provider comes in and sees nothing defined for "backup=" and thinks everything is okay. Then when a terraform apply tries to switch it from 1->0 it doesn't send anything through as a "backup=" value so Proxmox just accepts that as the default of being backed up.

Hopefully this makes sense!

**Comment by tnyeanderson** [comment]
`backup` is supposed to be an integer. Try `backup = 0` instead.

**Comment by n8rade** [comment]
> `backup` is supposed to be an integer. Try `backup = 0` instead.
> 
> https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#disk-block

I didn't provide an example in my text but I believe I was using integers as you can see the backup being set appropriately in some of the examples.

If you're referencing the original reporter's `backup = "0"`, does that matter? If I'm understanding this correctly HCL will automatically convert integers to strings: https://developer.hashicorp.com/terraform/language/expressions/types#type-conversion

**Comment by tnyeanderson** [comment]
Identified the issue: the `backup` parameter is not checked in [this function](https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/config_qemu.go#L1149) from the `proxmox-api-go` package. So the issue needs to be fixed there. Don't see any correlated issues in that project, so I will create one, link it here, and open my PR in that repo.

**Comment by tnyeanderson** [comment]
Fixed in https://github.com/Telmate/proxmox-api-go/pull/231
