### ISSUE TITLE
how to create multiple vm

### ISSUE THREAD

**Issue by javiermiras88** [Telmate/terraform-provider-proxmox#473]
I have the following configuration createvm.tf:

```
terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
    }
  }
}

provider "proxmox" {
  pm_api_url          = "...................."
  pm_api_token_id     = var.id
  pm_api_token_secret = var.token
  pm_tls_insecure     = true
}

locals {
  template = "plantilla-debian-11"
  vm = "master"
  vmid = 210
  ip_vm = "10.0.0.${local.vmid}"
  ip_vm_mask = "10.0.0.${local.vmid}\\/24"
  cores = 1
  vcpus = 1
  memoria = 3072
  disco = "32G"
  os_type = "ubuntu"
  qemu_os ="l26"
  etc_hosts_local = "127.0.0.1 localhost"
  etc_hosts_vm = "${local.ip_vm} ${local.vm}"

}

resource "proxmox_vm_qemu" "vm" {
  target_node = "proxmox"
  count       = 1
  agent       = 1
  name        = local.vm
  vmid        = local.vmid
  qemu_os     = local.qemu_os
  os_type     = local.os_type
  
  clone      = local.template
  full_clone = true
  
  cores     = local.cores
  vcpus     = local.vcpus
  memory    = local.memoria
  onboot    = true
  oncreate  = true

  disk {
    size    = local.disco
    type = "scsi"
    storage = "local-lvm"
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
  }

  connection {
    type        = "ssh"
    user        = "root"
    private_key = ..........
    host        = self.ssh_host
    port        = self.ssh_port
    agent       = false
  }
```

Can you tell me an example of how I can create 3 servers at the same time with different names and different ips ??? The above code works correctly and creates a single server correctly, the remote exec would be missing that I have not included in the code.

**Comment by Syntax3rror404** [comment]
Like this:

```terraform
resource "proxmox_vm_qemu" "proxmox_vm" {
  target_node       = var.pve_cluster_node
  pool              = var.pve_folder_path
  numa              = var.vm_numa
  count             = var.vm_count
  name              = count.index > 0 ? "${var.vm_name}-${count.index + 1}" : var.vm_name
....
```

**Comment by Syntax3rror404** [comment]
Use the 2.8.0 version 2.9.* are very unstable

**Comment by mleone87** [comment]
@Syntax3rror404  pls stop reporting in every issue that 2.9 is not working, it actually works fine. 
If you do not agree, open a **DETAILED**, well formatted issue with a complete example that fails:

- clean tf file, no modules
- complete logs
- template configuration
- **proxmox host specs, including storage config**

p.s. did you just miss the good old clone_wait feature? the actual logic tries 3 times to clone a disk!
p.s.2 I already tried to listen from proxmox team why cloning a **raw disk** on a **local storage** could bring to error 500 or error 596 but they do not care(they just answered to use a faster machine, who would have thought, we do not own a private AWS datacenter) and I bet that's your case but I'm just guessing since you do not provide precise infos.
p.s.3 I fixed this problem(that just appears on my **slowest mechanical hdd notebook**) using thin-provisioning storage and qcow2 format

**Comment by Syntax3rror404** [comment]
@mleone87 No, I don't stop writing that they shouldn't use the latest version because I can't recommend it to anyone. I use enterprise hardware. In my case an IBM System x3650 with 1 TB RAM and an LSI Raid controller with 8x 10K SAS hard disks and latest PVE version. 

Yes, the 2.9.3 works well if you only build one machine. But in my case I build for example rancher downstream clusters with 4-5 nodes and that only works with 2.8.0. And many like this issue here show that others want to do the same.

And that's only because, since 2.9.0, these 500 qemu errors have occurred sporadically during the cloning process. So the versions are not stable and I can't recommend them to use anyone. On the same server with vmware vsphere this does not happen with another provider that does the same.

I wrote that in a separate post, see https://github.com/Telmate/terraform-provider-proxmox/issues/467 but nobody answers

p.s clone_wait is deprecated now. If I use it anyway, I get completely different errors. The only working version is 2.8.0

**Comment by BaldFabi** [comment]
As @mleone87 already mentioned. Could you please (at least) provide (in your own issue) the following information

- clean tf file, no modules
- complete logs
- template configuration
- proxmox host specs, including storage config

You can't be serious about #467. It's copy pasting a log without any additional information and not even using markdown properly. I'm down to solve "your" problem but I'm not really motivated if the basic information are missing and I assume that I'm not the only one who feels that way.

**Comment by javiermiras88** [comment]
The fact is that I have managed to create 3 machines at the same time but now the error comes when supplying them, in the remote-exec it stays in a loop and does not execute the commands, does anyone know the solution ???

```
variable "vms" { 
  default = {
    201 = {"name" = "master01","ip" = "10.0.0.201" },
    202 = {"name" = "master02","ip" = "10.0.0.202" }, 
    203 = {"name" = "worker01","ip" = "10.0.0.203" }

  }
resource "proxmox_vm_qemu" "vm" {

  for_each = var.vms 

  name        = each.value.name
  vmid        = each.key

connection {
    type        = "ssh"
    user        = "root"
    private_key = file("~/.ssh/id_rsa")
    host        = each.value.ip
    port        = self.ssh_port
    agent       = false
  }

  provisioner "remote-exec" {
    inline = [
      "sudo hostnamectl set-hostname ${each.value.name}",

```

**Comment by BaldFabi** [comment]
Just to confirm this. It worked fine until you added the `provisioner` section? Are you able to connect to this machines manually?

**Comment by javiermiras88** [comment]
> Solo para confirmar esto. ¿Funcionó bien hasta que agregaste la `provisioner`sección? ¿Puede conectarse a estas máquinas manualmente?

yes, everything works correct , in fact if I put `host = self.host `it changes the name but only on a server

**Comment by mleone87** [comment]
how do you configure the hosts? cloud init? cant see any config in your tf

**Comment by javiermiras88** [comment]
> ¿Cómo se configuran los hosts? inicio en la nube? No puedo ver ninguna configuración en tu tf

in local, I have a debian template, and from this my config makes a full clone for each server

**Comment by mleone87** [comment]
I dont understand how you change on the 2nd and 3rd server with that configuration

**Comment by javiermiras88** [comment]
> No entiendo cómo se cambia la ip en el segundo y tercer servidor con esa configuración

sed -i 's/^.*address.*/\taddress ${local.ip_vm_mask}/' /etc/network/interfaces  witch remote-exec So if you have a better example tell me or how would you do it, thank you

**Comment by mleone87** [comment]
you cant remote exec a to a vm without know it's ip before, that's your problem
make a cloud init ready template and use the syntax on the docs to provision the vms with that, then do your stuff

**Comment by javiermiras88** [comment]
the problem this ` host        = each.value.ip    `    and the solution  `host        =self.host`

**Comment by mleone87** [comment]
@javiermiras88  thats a working config with a cloud init tamplate

```
resource "proxmox_vm_qemu" "cloudinit-test" {

  count       = 1
  name        = "qemu-vm${count.index + 1}"
  desc        = "A vm"
  target_node = "yournode"
  pool        = "yourpoolifany"

  # The template name to clone this vm from
  clone = "yourtemplate"

  # Activate QEMU agent for this VM
  agent = 1

  os_type = "cloud-init"
  qemu_os = "l26"
  cores   = 2
  sockets = 1
  cpu     = "host"
  memory  = 2048
  scsihw  = "virtio-scsi-pci"

  # Setup the disk
  disk {
    size    = "20G"
    type    = "virtio"
    storage = "local"
  }

  # Setup the network interface and assign a vlan tag: 256
  network {
    model  = "virtio"
    bridge = "vmbr0"
  }
  ipconfig0  = "ip=192.168.1.11${count.index + 1}/24,gw=192.168.1.1"
  ciuser     = "ubuntu"
  cipassword = "password"
  sshkeys    = "ssh-rsa  ......"
  ssh_user   = "ubuntu"
  connection {
    type     = "ssh"
    agent    = false
    user     = "ubuntu"
    password = "password"
    host     = self.default_ipv4_address
  }
  provisioner "remote-exec" {
    inline = [
      "hostname",
    ]
  }
}
```

**Comment by javiermiras88** [comment]
I already provided it in its day and it did not work nor backwards I prefer to do it my way

**Comment by javiermiras88** [comment]
version 2.8 remains in limbo I had to delete the vm by hand

**Comment by mleone87** [comment]
You should use latest version. Again, or your template has some very complex startup script that brings up the ip as you want or you Will never be able to remote exec to more than 1 VM.

Also, the template must have qemu guest agent enabled on startup. The cloud init images downloaded from distributions does not have agent installed

**Comment by Syntax3rror404** [comment]
If you want to clone conventionally with golden images instead of cloud-init, the machine-ID must be reset before cloning.

Use this command to reset the machine-id: (for example within packer with the shell provider)
`sudo truncate -s 0 /etc/machine-id`

After you have done that you can use the template with this provider here and you will get different IPs and then the remote exec will also work.

I hope that helps :)

**Comment by javiermiras88** [comment]
We are going to see you take me for a fool as, the first IP that the remote catches is 10.0.0.110 it is changed along with the name and the server and then the next one in a loop and it works correctly that you are going to truncate the machines are we crazy or what
