### ISSUE TITLE
Why do some values have defaults?

### ISSUE THREAD

**Issue by alteredtech** [Telmate/terraform-provider-proxmox#487]
When creating a vm from a clone, I do not understand why there is a need for a default value for memory, cpu cores, sockets, etc. Those should already be defined by the clone. If we wish to alter those values then we should be able to specify the value for each field. Is this a limitation of the API that those value MUST be specified?

For reference, I am using packer to create my templates, I would like to quickly clone those templates since they are already at the base line of what I need. Terraform just needs to deploy them to proxmox with any minor changes I may need to make to them.

**Comment by instag1b** [comment]
Proxmox doesn't require (or even provide) virtual hardware related parameters at the `/clone` endpoint (see [docs](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/clone)). The reason why the hardware settings of your template are overriden is because `config.UpdateConfig()` is called [here](https://github.com/Telmate/terraform-provider-proxmox/blob/a44e0765653b9d60c93805740748db9ce7849354/proxmox/resource_vm_qemu.go#L865) after cloning the template. This will then apply default values for arguments where no value is provided.
Maybe introducing a switch/boolean to choose between keeping or overriding template hardware configuration would help?

**Comment by r-ushil** [comment]
Came across this. Honestly, don't bother. Here's a script that changed some cloud-init values. Wish I did this instead of wasting a day with the crashing plugin.

`#!/bin/bash

NODE_NAME="octopus2"
TEMPLATE_VMID=9001
CI_USER="swarm"
CI_PASSWORD="swarm"
SSH_KEY_PATH="${HOME}/.ssh/id_rsa.pub"
BASE_IP="192.168.2."
GW="${BASE_IP}1"
VMID_BASE=200


qm set ${TEMPLATE_VMID} --sshkey "${SSH_KEY_PATH}"
qm set ${TEMPLATE_VMID} --ciuser "${CI_USER}" --cipassword "${CI_PASSWORD}"

for COUNT in {1..3}; do
  IP="${BASE_IP}$((COUNT + 2))"
  VMID=$(($VMID_BASE + $COUNT))
  IPCONFIG="ip=${IP}/24,gw=${GW}"
  VM_NAME="swarm-vm${COUNT}"

  echo "Creating VM: ${VM_NAME} with IP: ${IP} and VMID: ${VMID}"

  qm clone ${TEMPLATE_VMID} ${VMID} --name "${VM_NAME}" --full true
  qm set ${VMID} --ipconfig0 "${IPCONFIG}"

  qm start ${VMID}

done`
