### ISSUE TITLE
How to retrive lxc ip after creation

### ISSUE THREAD

**Issue by DblK** [Telmate/terraform-provider-proxmox#540]
I wish to do two things:
1. Be able to have an output variable with the ip of the lxc container
2. Be able to remote-exec some command in the newly created lxc.

For the 2. I could not succeed because for the `connection` block I need the `host`.

Any advices or fix?

**Comment by mleone87** [comment]
actually, sadly, there is no easy way to get containers ip like vms :(

**Comment by tuxvador** [comment]
instead of "dhcp", the host value need to be the hostname of the container. In my case i have setup a pf in automatic install on proxmox with : https://github.com/tuxvador/PROXMOX_PFSENSE_AUTOINSTALL or use /etc/hosts. The thing is your proxmox server needs to be able to resolve the value you wil put in host. like : 

`provisioner "remote-exec" {
    connection {
      type        = "ssh"
      user        = "root"
      host        = "provisioning"
      private_key = file(var.provisioning.private_key)
      timeout     = "5m"
    }`

then when deploying your container, set ssh_public_keys = file(var.provisioning.public_key) password authentication wont work because root passord logging is disabled at boot. Feel free to ask any question
