### ISSUE TITLE
agent = 1 hangs if no IPv4 address is assigned

### ISSUE THREAD

**Issue by ipsecguy** [Telmate/terraform-provider-proxmox#573]
Version 2.9.10
When cloning from cloudimage and enabling agent = 1 the provider waits for the IPv4 information becoming available from qemu-guest-agent.
It waits indefinitly when not getting IPv4 information, i.e. IPv6 Link-Local and Public is available and visible in Proxmox. It also waits indefinitly when the guest agent is not running.

I am not using ssh based provisioning, so this "wait for working IPv4" does not make sense in this case I think.

**Comment by Syntax3rror404** [comment]
Are you sure that the vm gets an ip from the dhcp? Can you post your code?

**Comment by Tinyblargon** [comment]
Hi, could you run the provider again with environment variable [`TF_LOG` set to `DEBUG`](https://www.terraform.io/internals/debugging) and post the output here? I currently think that the code enters [this loop](https://github.com/Telmate/terraform-provider-proxmox/blob/2d09a21a25053ea4031331d4bd7812740ed54afe/proxmox/resource_vm_qemu.go#L1930-L1952) and never exits because it only checks for a ipv4 address.

**Comment by Syntax3rror404** [comment]
I also think that this tf provider doesn't support ipv6 at this time because it only read ipv4 addresses from proxmox.
