### ISSUE TITLE
Error: only root can modify 'usb0' config for real devices

### ISSUE THREAD

**Issue by nununo** [Telmate/terraform-provider-proxmox#764]
Hello,

I'm getting this error when trying to add an USB HDD passthrough to an existing VM by adding this block to the resource:

```terraform
  usb {
    host = "1058:0730"
    usb3 = true
  }
```

While the error is self-evident, I still don't understand why it happens since my API token id (`root@pam!terraform`) is associated with the `root` user and is configured with NO privilege separation.

Please advise.

Thank you.

**Comment by nununo** [comment]
I'm now running Proxmox 8 with provider version `2.9.14` and this is the full log output:

```
  Error: only root can set 'usb0' config for real devices
  
    with proxmox_vm_qemu.docker[0],
    on vm-1000-docker.monte.nunogodinho.com.tf line 1, in resource "proxmox_vm_qemu" "docker":
     1: resource "proxmox_vm_qemu" "docker" {
```

I don't know what to do since my API token is already associated with the `root` user.

**Comment by n-asenov** [comment]
I had a similar issue with PCI passthrough and I solved it by authenticating with the root username and password instead of with an API token.

I think the Proxmox team added a hard check in Proxmox 8 and now only the 'root@pam' user can pass through non-mapped PCI/USB devices.

In your case 'root@pam!terraform' is different from  'root@pam' and that's why you can't pass through the non-mapped USB device.

**Comment by nununo** [comment]
Thank you @n-asenov. I will try your suggestion.

**Comment by nununo** [comment]
It worked @n-asenov. Thank you!
