### ISSUE TITLE
cannot process parameter `serial`

### ISSUE THREAD

**Issue by ebCrypto** [Telmate/terraform-provider-proxmox#795]
How to reproduce:
1. create a proxmox VM with `terraform apply`
2. Using the proxmox UI, update the VM to passthrough a disk with serial number

then any subsequent `terraform apply` will result in 

```
Error: proxmox Provider Error: proxmox API returned new disk parameter 'serial' we cannot process
```

**Comment by rilesdun** [comment]
Seems you should try creating manually as specified in the documentation instead of the UI

I would expect issues here as noted in - https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#attribute-reference


<h3 id="serial-block" style="box-sizing: inherit; margin: 24px 0px 0px; padding: 12px 0px; font-size: 1rem; font-weight: 600; text-transform: none; color: rgb(0, 0, 0); letter-spacing: normal; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#serial-block" class="anchor" name="serial-block" style="box-sizing: inherit; color: inherit; cursor: pointer; text-decoration: none; transition: color 0.1s ease 0s; position: relative;">Serial Block</a></h3><p style="box-sizing: inherit; margin: 0px; padding: 12px 0px; line-height: 1.7; max-width: 888px; color: rgb(31, 33, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Create a serial device inside the VM (up to a maximum of 4 can be specified), and either pass through a host serial device (i.e. /dev/ttyS0), or create a unix socket on the host side. The order in which<span> </span><code style="box-sizing: inherit; -webkit-font-smoothing: auto; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; background-color: rgb(247, 248, 250); color: rgb(198, 42, 113); font-size: 12px; font-weight: 500; padding: 4px; border: 1px solid rgb(220, 224, 230); border-radius: 2px; text-align: center; height: 16px; margin: 0px 4px;">serial</code><span> </span>blocks are declared does not matter.</p><p style="box-sizing: inherit; margin: 0px; padding: 12px 0px; line-height: 1.7; max-width: 888px; color: rgb(31, 33, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: inherit; color: rgb(53, 53, 53); font-weight: 700;">WARNING</strong>: Use with caution, as the docs indicate this device is experimental and users have reported issues with it.</p><p style="box-sizing: inherit; margin: 0px; padding: 12px 0px; line-height: 1.7; max-width: 888px; color: rgb(31, 33, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">See the<span> </span><a target="_blank" rel="nofollow noopener" href="https://pve.proxmox.com/pve-docs/chapter-qm.html#qm_options" style="box-sizing: inherit; color: rgb(71, 94, 198); cursor: pointer; text-decoration: none; transition: color 0.1s ease 0s;">options for serial</a><span> </span>in the PVE docs for more details.</p>

Argument | Type | Default Value | Description
-- | -- | -- | --
id | int |   | Required The ID of the serial device. Must be unique, and between 0-3.
type | str |   | Required The type of serial device to create. Options: socket, or the path to a serial device like /dev/ttyS0.

[Serial Block](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#serial-block)
Create a serial device inside the VM (up to a maximum of 4 can be specified), and either pass through a host serial device (i.e. /dev/ttyS0), or create a unix socket on the host side. The order in which serial blocks are declared does not matter.

WARNING: Use with caution, as the docs indicate this device is experimental and users have reported issues with it.

See the [options for serial](https://pve.proxmox.com/pve-docs/chapter-qm.html#qm_options) in the PVE docs for more details.

Argument	Type	Default Value	Description
id	int		Required The ID of the serial device. Must be unique, and between 0-3.
type	str		Required The type of serial device to create. Options: socket, or the path to a serial device like /dev/ttyS0.
