### ISSUE TITLE
Terraform provider proxmox v2.9.14 plugin crashed -  Proxmox 8.1.3.

### ISSUE THREAD

**Issue by syafi-dev** [Telmate/terraform-provider-proxmox#869]
I just upgraded my Proxmox to version 8.1.3. When I run terraform plan, it provides me this error:

=======
Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 13 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0x14000253038, 0x14000253038?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x3b34
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0x140000e0000, {0x103361ee0?, 0x140001a4050})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1475 +0x324
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0x103361ee0?, 0x140001a4050?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446 +0x24
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10349e9a0?, {0x10349e9a0?, 0x14000744cf0?}, 0xd?, {0x103361ee0?, 0x140001a4050?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:712 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140003b67e0, {0x10349e9a0, 0x14000744cf0}, 0x140005bb2b0, {0x103361ee0, 0x140001a4050})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000440b88, {0x10349e9a0?, 0x14000744bd0?}, 0x14000634240)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140001223c0, {0x10349e9a0?, 0x14000744420?}, 0x1400036c9c0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x103467a60?, 0x140001223c0}, {0x10349e9a0, 0x14000744420}, 0x140001a20e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000458000, {0x1034a2540, 0x1400031e1a0}, 0x140008b57a0, 0x1400045ac00, 0x10393f830, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x14000458000, {0x1034a2540, 0x1400031e1a0}, 0x140008b57a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed

=======

Your help is highly appreciated. Thank you.

**Comment by dmbrownlee** [comment]
I also get a similar stack trace generated when trying to use "terraform import" against Proxmox 8.1.3 with plugin 2.9.14.

=======
Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 83 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000017088, 0xc000017088?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc000312b00, {0xb66f60?, 0xc0002b6dc0})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1475 +0x457
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0xb66f60?, 0xc0002b6dc0?})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xdd7840?, {0xdd7840?, 0xc0003056b0?}, 0xd?, {0xb66f60?, 0xc0002b6dc0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003a87e0, {0xdd7840, 0xc0003056b0}, 0xc0002d0dd0, {0xb66f60, 0xc0002b6dc0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000432b88, {0xdd7840?, 0xc000305590?}, 0xc00050c2c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003183c0, {0xdd7840?, 0xc000304990?}, 0xc00008cc60)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc6bc20?, 0xc0003183c0}, {0xdd7840, 0xc000304990}, 0xc000116000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044c000, {0xddb420, 0xc000451380}, 0xc0004ce000, 0xc00044eb40, 0x128f770, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00044c000, {0xddb420, 0xc000451380}, 0xc0004ce000, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
=======

Thank you.

**Comment by hwts** [comment]
Similar problem when trying to create virtual machines - Proxmox 8.1.3
======================
Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:
panic: interface conversion: interface {} is string, not float64
goroutine 29 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000683088, 0xc000683088?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc000152400, {0xb66f60?, 0xc00018c0f0})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1475 +0x457
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0xb66f60?, 0xc00018c0f0?})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xdd7840?, {0xdd7840?, 0xc00031fb90?}, 0xd?, {0xb66f60?, 0xc00018c0f0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00035c7e0, {0xdd7840, 0xc00031fb90}, 0xc00016dd40, {0xb66f60, 0xc00018c0f0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003e6b70, {0xdd7840?, 0xc00031fa70?}, 0xc0000b3040)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000ba3c0, {0xdd7840?, 0xc00079a0c0?}, 0xc0004809c0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc6bc20?, 0xc0000ba3c0}, {0xdd7840, 0xc00079a0c0}, 0xc000194070, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000400000, {0xddb420, 0xc000093520}, 0xc0002d10e0, 0xc000402c00, 0x128f770, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000400000, {0xddb420, 0xc000093520}, 0xc0002d10e0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by batonogov** [comment]
I'll try to solve the problem as written [here](https://github.com/Telmate/terraform-provider-proxmox/issues/863). But in the end I changed the provider.

**Comment by batonogov** [comment]
> > I'll try to solve the problem as written [here](https://github.com/Telmate/terraform-provider-proxmox/issues/863). But in the end I changed the provider.
> 
> Same issue here, what did you change it to?

I'm at the stage of selecting a provider and I've had problems before.

**Comment by vinny147-BIG** [comment]
Same issue after upgrading to 8.1

**Comment by Neels-v-Wyk** [comment]
Not a drop in replacement but a well maintained alternative: https://github.com/bpg/terraform-provider-proxmox

**Comment by centerionware** [comment]
My setup is running 2x proxmox servers, one is 8.1.3, the other is 8.0.4. I'm running terraform from a vm on the 8.1.3 machine, which connects to the 8.0.4 machine to run it to thin clone a vm on the 8.1.3 and launch it on the 8.1.3(cause of routing vm's can't access their host's ip). 
Hit this same issue, tried to use TheGameProfi's fork which seemed to work at first, but then the cloned vm doesn't boot, saying `Boot failed: not a bootable disk`
The exact same configuration worked before upgrading to 8.1.3 on the one server (they weren't the same versions before), I use the script to destroy and rebuild dedicated vm's to host gitlab runners and easily be able to wipe&recreate them
My solution will probably be to downgrade proxmox for now.

**Comment by luifrancisco** [comment]
I also got the same problem of `Boot failed: not a bootable disk` when using TheGameProfi's fork. I am using a cloud init template for cloning which used to work in an older version of PVE but now it seems like Instead of resizing the original cloud-init disk assigned to scsi0 (for example), it actually creates a new disk and assigns it to scsi0. The original disk gets unmounted and shows "Unused Disk" in the hardware tab. Still checking how to work around this.

**Comment by morsik** [comment]
@luifrancisco workaround for failed boot is already there and it works fine (tested today): https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1870907419

**Comment by thomas-numbskulls** [comment]
> Same issue after upgrading to 8.1. Further researched this and found that this provider doesn't seem to be supporting this anymore. I moved to [here](https://registry.terraform.io/providers/TheGameProfi/proxmox/2.9.15) and it worked. Make sure you add SDN permissions to your role.

can you provide your providers.tf contents. I'm getting. 

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/telmate/proxmox" requires explicit configuration. Add a provider block to
│ the root module and configure the provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: you must specify an endpoint for the Proxmox Virtual Environment API (valid: https://host:port)
│
│   with provider["registry.terraform.io/telmate/proxmox"],
│   on <empty> line 0:
│   (source code not available)
│
╵

**Comment by MARVELMafia** [comment]
> > Same issue after upgrading to 8.1. Further researched this and found that this provider doesn't seem to be supporting this anymore. I moved to [here](https://registry.terraform.io/providers/TheGameProfi/proxmox/2.9.15) and it worked. Make sure you add SDN permissions to your role.
> 
> can you provide your providers.tf contents. I'm getting.
> 
> Planning failed. Terraform encountered an error while generating this plan.
> 
> ╷ │ Error: Invalid provider configuration │ │ Provider "registry.terraform.io/telmate/proxmox" requires explicit configuration. Add a provider block to │ the root module and configure the provider's required arguments as described in the provider documentation. │ ╵ ╷ │ Error: you must specify an endpoint for the Proxmox Virtual Environment API (valid: https://host:port) │ │ with provider["registry.terraform.io/telmate/proxmox"], │ on line 0: │ (source code not available) │ ╵

for some reason I have also started to get this. It was working file up till a month ago not sure what happened?

**Comment by chakraborty29** [comment]
I was running into the same issues, and then when I switched over to v3.0.1-rc3, I faced a different issue where the the vm would get assigned an IP from DHCP and not from cloud-init. After some hours, I looked at the example provided: (cloudinit_example.tf)[https://github.com/Telmate/terraform-provider-proxmox/blob/master/examples/cloudinit_example.tf]

And changed my config to:
```
disks {
        ide {
            ide3 {
                cloudinit {
                  storage = "local-lvm"
                }
            }
        }
        virtio {
            virtio0 {
                disk{
                    storage = "local-lvm"
                    size = "${var.size}"  # Set the storage size here
                }

            }
        }
    }

boot = "order=virtio0"
```

**Comment by morsik** [comment]
@2000aliali changing provider to this one: https://registry.terraform.io/providers/bpg

It's still maintained and all those bugs are fixed and few features added too.
