### ISSUE TITLE
`oncreate` is deprecated but `vm_state` is not a replacement

### ISSUE THREAD

**Issue by pescobar** [Telmate/terraform-provider-proxmox#893]
If I use `oncreate = false` I get error `deprecated, use vm_state instead` but `vm_state` doesn't work as replacement for `oncreate`

If I use `vm_state = stopped` the VM will be stopped every time I execute the terraform code. If I use `vm_state = running` the machine will be started right after I create it. None of this replace `oncreate = false`. What I need is that the machine stays off only when I first create it and it stays off until I decide to start it.

To give some extra background, this is my workflow:

  * Create the qemu VM in proxmox (keep it off)
  * Register the qemu VM in MAAS using the [proxmox power driver](https://maas.io/docs/setting-up-power-drivers#heading--proxmox)
  * MAAS powers on the machine. The machine boots over pxe to deploy the OS 

This workflow is working fine with `proxmox 7.x` and `Telmate/proxmox 2.9.14` but it doesn't work anymore since we upgraded to `proxmox 8.x` and `TheGameProfi/proxmox 2.9.15` and `oncreate` is deprecated.

Trying to workaround this problem we tried to use `define_connection_info = false` so at least terraform doesn't wait for the VM to boot and get an ip but this triggered another issue reported in https://github.com/Telmate/terraform-provider-proxmox/issues/891

**Comment by Tinyblargon** [comment]
@pescobar If i understand correctly you want the `vm_state` to not be updated by terraform?

So it would create the VM in `stopped` mode but not stop it on a subsequent run?

**Comment by pescobar** [comment]
Hi @Tinyblargon 

With older versions of the provider the `oncreate` flag was working as the "Start after created" checkbox in the VM creation form (see red circle in the attached screenshot)

![vm-creation-proxmox](https://github.com/Telmate/terraform-provider-proxmox/assets/103797/45b60ce0-0300-45ad-b915-bc198cdbefdc)

In my understanding `vm_state` and `oncreate` are different and `vm_state` cannot replace `oncreate`. Before the `oncreate` option was deprecated I was using `oncreate = false` and `vmstate = running` and this config is no longer possible.

I hope I made it more clear. Let me know if you have any doubts.

**Comment by mleone87** [comment]
@pescobar @Tinyblargon the **"start after created"** in the proxmox gui is just a shortcut that makes proxmox start the vm for you, there is no api counterpart for it.

the `oncreate` and `vm_state` are the result of different people trying to solve the same problem in various ways without considering the previous work. This is a great example of contributions that we should manage better in the future.

In your specific case, you can define your vm with `vm_state = stopped` and then after doing your fiddling with MAAS, you update your terraform with `vm_state = running` and you should get what you want, since the terraform run will detect the vm is already running and simply update the tfstate

**Comment by Tinyblargon** [comment]
@mleone87 we could introduce a `vm_state = stared` that would set the state to `running` during creation and not set it during update.

**Comment by Tinyblargon** [comment]
@pescobar This feature has been added to the roadmap
