### ISSUE TITLE
Question [3.0.1-RC1] -- resize disk with full clone

### ISSUE THREAD

**Issue by Arvoreen** [Telmate/terraform-provider-proxmox#919]
I can not figure out how to setup my `disks {}` block so that I can just resize the primary/os boot disk of a full clone.

For my setup, I have a template VM setup with
ide2 -- cloud init drive
scsi0 -- 8G os/boot drive

I want to configure a VM as a full clone of the template but resize the primary/os boot drive to 40G.
No matter what I try, it will always create a new, empty 40G drive, and take the original 8G clone image and unassign it from the VM.  

Does anyone have a working example I can follow?

**Comment by hestiahacker** [comment]
I remember having an issue where deploying once would result in the disk being the same size and then running `terraform apply` a second time (without changing anything) would trigger the disk to resize to the correct size. However I can't find that post now, nor can I reproduce the behavior in 3.0.1-rc1. Here's a small example:

`provider.tf`
```
# Define the usual provider things
terraform {
  required_providers {
    proxmox = {
      #source = "registry.example.com/telmate/proxmox"
      #version = ">=1.0.0"
      source = "Telmate/proxmox"
      #version = "=2.9.11"
      version = "=3.0.1-rc1"
    }
  }
  required_version = ">= 0.14"
}

#provider "proxmox" {
#  pm_log_enable = true
#  pm_log_file   = "terraform-plugin-proxmox.log"
#  pm_debug      = true
#  pm_log_levels = {
#    _default    = "debug"
#    _capturelog = ""
#  }
#}
```

`issue919.tf`
```
resource "proxmox_vm_qemu" "server" {
  name              = var.name
  target_node       = var.target_node
  clone             = "debian-12"
  os_type           = "cloud-init"
  scsihw            = "virtio-scsi-pci"
  disks {   
    virtio {
      virtio0 {
        disk {
          size            = 20
          cache           = "writeback"
          storage         = "local-zfs"
        }
      }
    }
  }
  network {         
    model           = "virtio"
    bridge          = "vmbr0"
  }

  # Cloud Init Settings
  # Reference: https://pve.proxmox.com/wiki/Cloud-Init_Support
  cloudinit_cdrom_storage = var.storage_backend
  ipconfig0 = "ip=${var.ip_address}/${var.cidr},gw=${var.gateway}"
  nameserver = var.nameservers
  sshkeys = file("${path.root}/test.pub")
} 
```

and an example of what you might find in `vars.tf`:
```
variable "target_node" { default = "larry" }
variable "ip_address" { default = "192.168.73.57" }
variable "cidr" { default = "24" }
variable "gateway" { default = "192.168.73.1" }
variable "nameservers" { default = "192.168.73.100 192.168.73.200" }
variable "name" { default = "test.example.com" }
variable "storage_backend" { default = "local-zfs" }
```

The template I am cloning has a 10GB boot disk and I'm making it 20GB. During the clone operation, but before the move, it shows the new VM also has a 10GB drive. After the move operation, it is updated to be 20GB. I only know this because I was watching the deployment in the Proxmox web interface very closely.

**Comment by valkiriaaquatica** [comment]
> I can not figure out how to setup my `disks {}` block so that I can just resize the primary/os boot disk of a full clone.
> 
> For my setup, I have a template VM setup with ide2 -- cloud init drive scsi0 -- 8G os/boot drive
> 
> I want to configure a VM as a full clone of the template but resize the primary/os boot drive to 40G. No matter what I try, it will always create a new, empty 40G drive, and take the original 8G clone image and unassign it from the VM.
> 
> Does anyone have a working example I can follow?

Hi @Arvoreen  have you finally found a way to do that? I'm also struggling because no resize is make using this provider... and when adding a disk, the boot failes because  treies to boot from the disk attached and not the one where the template comes from...

If you found a solution, you mind sharing it? :)

**Comment by Tinyblargon** [comment]
@valkiriaaquatica [This guide](https://github.com/Telmate/terraform-provider-proxmox/blob/f52c575655e69b479299f192e24cccec16ca8578/docs/guides/cloud-init%20getting%20started.md) shows how to configure the disk amongst other things. It is written for `3.0.1rc4`.
