### ISSUE TITLE
Issue with upgrading old projects to 3.0.1-rc1 version

### ISSUE THREAD

**Issue by sajjadG** [Telmate/terraform-provider-proxmox#933]
Hello everyone, I wish you're having a good day.

When I use `3.0.1-rc1` for creating a new project it works. But when I upgrade my older projects to `3.0.1-rc1` version I get this error:

```terraform
╷
│ Error: bool is required
│ 
│ 
╵
```

old project disk layout is the old one in tfstate file. I think that's the cause of this error.

**Comment by hestiahacker** [comment]
This looks like the same thing that I fixed in #702 but it has not been merged into the default branch yet. https://github.com/Telmate/terraform-provider-proxmox/pull/923

If you are willing to edit your tfstate file to replace "backup": 0 with "backup": false (or 1 with true) and try deploying again, that will confirm that this is the same issue. If it's some other field, please let me know.

The thing holding up the merge request is uncertainty as to whether we need to apply this fix to all fields that are booleans, so if you can confirm that the only one that is a problem is the "backup" field it might help get that merge request in sooner rather than later.

**Comment by hestiahacker** [comment]
More detailed information about updating the tfstate file can be found in [this comment](https://github.com/Telmate/terraform-provider-proxmox/issues/702#issuecomment-1566700961)

**Comment by hestiahacker** [comment]
The merge request https://github.com/Telmate/terraform-provider-proxmox/pull/923 has been merged into the default branch. When a v3.0.1-rc2 release candidate is cut, we can verify that it fixes this issue. The 3.x release is being tracked in #910 and #913.
