### ISSUE TITLE
Support cloud-init as scsi drive for machine type q35

### ISSUE THREAD

**Issue by tuxthepenguin84** [Telmate/terraform-provider-proxmox#973]
Hi,

After much trial and error I've discovered an issue where if you are using machine type q35, cloud-init will not run because terraform-provider-proxmox attaches the cloud-init drive as ide. My work around right now is to set hastate to stopped, deploy my VM, delete the cloud-init drive as ide and re-add as scsi. Now when I start my VM for the first time it will successfully run cloud-init. I then go back and update terraform to hastate running and delete `cloudinit_cdrom_storage`. I am using the latest changes from master at the time of creating this issue.

**Comment by justadri** [comment]
I'm not sure if this is also/separately a q35 machine type issue, but the inability to use an IDE cloudinit drive is a known issue with Proxmox and OVMF BIOS, e.g. https://forum.proxmox.com/threads/cloudinit-ssh-error-on-startup.141845/ . The Telmate provider is hard-coded to create the cloudinit drive as ide3. But since both OVMF and q35 are needed for PCIe passthrough, using a SCSI cloudinit drive should be supported.
